alias ll='ls -alh'
alias cp='cp -i'
alias mv='mv -i'

alias gb='git branch'
alias gch='git checkout'
alias gs='git status'
alias gd='git diff'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push origin HEAD'
alias gfp='git push -f origin HEAD'
alias gl='git log'

alias kenkosetup='bundle exec rake carthage:bootstrap && xcodegen && bundle exec pod install'
alias kenkoopen='open kenko.xcworkspace'
